// import {Geist, Geist_Mono} from "next/font/google";
import type {Metadata} from "next";
import "./globals.css";
import Header from "@/component/UI/Header";

export const metadata: Metadata = {
    title: "itsa studio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased store`}>
                <Header></Header>
                <main className="flex flex-col flex-1">{children}</main>
            </body>
        </html>
    );
}
